apiVersion: v1
kind: Service
metadata:
  name: {{ include "pyprom.fullname" . }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.deployment.metricsPort }}"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/probe: "true"
  labels:
    {{- include "pyprom.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.deployment.appPort }}
      targetPort: app
      protocol: TCP
      name: app
    - port: {{ .Values.deployment.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "pyprom.selectorLabels" . | nindent 4 }}
